services:
  postgresql:
    image: postgres:17.6-alpine
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: SaintSeiya013
      POSTGRES_DB: credito
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./postgres:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"
    networks:
      creditos-network:
        aliases:
          - postgresql
  kafka:
    image: bitnami/kafka:latest
    container_name: kafka
    restart: on-failure
    ports:
      - 9092:9092
    environment:
      KAFKA_CFG_NODE_ID: ${KAFKA_CFG_NODE_ID}
      KAFKA_CFG_ZOOKEEPER_CONNECT: ${KAFKA_CFG_ZOOKEEPER_CONNECT}
      KAFKA_CFG_PROCESS_ROLES: ${KAFKA_CFG_PROCESS_ROLES}
      KAFKA_CFG_LISTENERS: ${KAFKA_CFG_LISTENERS}
      KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP: ${KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP}
      KAFKA_CFG_CONTROLLER_QUORUM_VOTERS: ${KAFKA_CFG_CONTROLLER_QUORUM_VOTERS}
      KAFKA_CFG_CONTROLLER_LISTENER_NAMES: ${KAFKA_CFG_CONTROLLER_LISTENER_NAMES}
    networks:
      creditos-network:
        aliases:
          - kafka
    depends_on:
      - zookeeper
  zookeeper:
    image: bitnami/zookeeper:latest
    container_name: zookeeper
    ports:
      - 2181:2181
    environment:
      ALLOW_ANONYMOUS_LOGIN: yes
  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    container_name: kafka-ui
    restart: always
    ports:
      - 8080:8080
    environment:
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:9092
      KAFKA_CLUSTERS_0_ZOOKEEPER: zookeeper:2181
    networks:
      creditos-network:
        aliases:
          - kafka-ui
    depends_on:
      - kafka
      - zookeeper
  falzoni-java-creditos-nf:
    image: falzoni-java-creditos-nf:1.0.0
    container_name: api
    build: 
      context: ./falzoni-java-creditos-nf
    environment:
      DATABASE_URL: jdbc:postgresql://postgresql/credito
      DB_USERNAME: postgres
      DB_PASSWORD: SaintSeiya013
    ports:
      - 8081:8080
    depends_on:
      - kafka
    networks:
      creditos-network:
        aliases:
          - falzoni-java-creditos-nf
  falzoni-creditos-web:
    image: falzoni-creditos-web:1.0.0
    container_name: web
    build: 
      context: ./falzoni-creditos-web
    ports:
      - 3000:80
    depends_on:
      - kafka
      - falzoni-java-creditos-nf
    networks:
      creditos-network:
volumes:
  db_data:
networks:
  creditos-network: